water_plant:
  name: Water Plant
  description: Mark a plant as watered and reset the watering countdown.
  fields:
    plant_id:
      name: Plant ID
      description: The unique identifier of the plant to water.
      required: true
      selector:
        text:

add_plant:
  name: Add Plant
  description: Add a new plant to monitor.
  fields:
    plant_name:
      name: Plant Name
      description: The display name for the plant.
      required: true
      selector:
        text:
    plant_type:
      name: Plant Type
      description: The type of plant from the database, or 'custom' for a custom plant.
      required: false
      selector:
        text:
    watering_mode:
      name: Watering Mode
      description: How to track watering (sensor-based or manual countdown).
      required: false
      default: "manual"
      selector:
        select:
          options:
            - value: "manual"
              label: "Manual Countdown"
            - value: "sensor"
              label: "Soil Humidity Sensor"
    humidity_sensor:
      name: Humidity Sensor
      description: The humidity sensor entity to monitor (required if using sensor mode).
      required: false
      selector:
        entity:
          domain: sensor
          device_class: humidity
    watering_interval:
      name: Watering Interval
      description: Number of days between waterings (for manual mode).
      required: false
      default: 7
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: "days"

remove_plant:
  name: Remove Plant
  description: Remove a plant from monitoring.
  fields:
    plant_id:
      name: Plant ID
      description: The unique identifier of the plant to remove.
      required: true
      selector:
        text:

update_plant_image:
  name: Update Plant Image
  description: Update the background image for a plant card.
  fields:
    plant_id:
      name: Plant ID
      description: The unique identifier of the plant.
      required: true
      selector:
        text:
    image_path:
      name: Image Path
      description: The path to the image file (relative to /config/www/).
      required: true
      selector:
        text:
