name: Planty - Plant Watering Manager
version: "1.0.0"
slug: planty
description: A comprehensive plant watering management system with beautiful dashboards and smart tracking
url: https://github.com/planty/planty
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
hassio_api: true
homeassistant_api: true
host_network: false
privileged:
  - SYS_RAWIO
devices:
  - /dev/mem:/dev/mem:rw
gpio: false
usb: false
uart: false
kernel_modules: false
environment:
  LOG_LEVEL: info
map:
  - share:rw
  - config:rw
options:
  log_level: info
  auto_create_dashboard: true
  image_storage_path: "/share/planty/images"
  backup_enabled: true
  backup_interval: 24
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  auto_create_dashboard: bool?
  image_storage_path: str?
  backup_enabled: bool?
  backup_interval: int(1,168)?
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web UI for plant management
webui: http://[HOST]:[PORT:8099]
panel_icon: mdi:leaf
panel_title: Planty
panel_admin: false
image: ghcr.io/planty/planty-addon-{arch}
